--THIS IS CALLED QUERY TO GET EMPLOYEE DATA
--

SELECT * FROM DEPARTMENTS;--FIRST SYNTEX

SELECT DEPARTMENT_NAME FROM DEPARTMENTS;--SECOND

SELECT DEPARTMENT_NAME,DEPARTMENT_ID FROM DEPARTMENTS;-- THIRED

SELECT DEPARTMENT_NAME, DEPARTMENT_ID FROM DEPARTMENTS;--FOURTH

SELECT * FROM EMPLOYEES, DEPARTMENTS;

SELECT EMPLOYEES.EMPLOYEE_ID, DEPARTMENTS.DEPARTMENT_ID FROM EMPLOYEES,DEPARTMENTS;

--DISTINCT KEYWORD----- DISPLAY RESULT WITHOUT DUPLICATE
SELECT DISTINCT DEPARTMENT_ID FROM DEPARTMENTS;

SELECT DISTINCT SALARY FROM EMPLOYEES;


SELECT  MAX_SALARY FROM JOBS;
SELECT DISTINCT MAX_SALARY FROM JOBS;

